title: "Snyk {{ snyk_pull_request_type }} PR (addresses {{ issue_count }} issues)"
branchName: "security/{{ issue_count }}-issues"
commitMessage: "fix: {{ issue_count }} Snyk issues"
description: |

  <b>Changes made:</b>
  - <b>{{ package_name }}</b>: {{ package_from }} ➡️ {{ package_to }}

  {{ #is_upgrade_pr }}
  
  <b>Upgrade PR:</b>
  
  📚 This PR has been opened to make sure our repositories are kept up-to-date.
  
  Review relevant docs for possible breaking changes.
  {{ /is_upgrade_pr }}
  {{ ^is_upgrade_pr }}
  {{ /is_upgrade_pr }}
  {{ #is_fix_pr }}
  
  <b>Fix PR:</b>
  
  🔧 This PR has been opened to fix a vulnerability by upgrading <b>{{ package_name }}</b> from <b>{{ package_from }}</b> to <b>{{ package_to }}</b>.
  
  Review relevant docs for possible breaking changes.
  {{ /is_fix_pr }}
  {{ ^is_fix_pr }}
  {{ /is_fix_pr }}
  {{ #is_backlog_pr }}
  
  🪵 This PR addresses a backlog item.
  
  {{ /is_backlog_pr }}
  {{ ^is_backlog_pr }}
  {{ /is_backlog_pr }}
  
  Snyk Org: [{{ snyk_org_name }}](https://app.snyk.io/org/{{ snyk_org_name }}/projects?groupBy=targets&searchQuery=&sortBy=highest+severity&filters[Show]=&filters[Integrations]=&before&after)
  To find more details, see this issue in the Snyk UI [{{ snyk_project_name }}]({{ snyk_project_url }})
  
  **Tickets:**
  {{ #jira_ids }}
  - Fixes {{ . }}
  {{ /jira_ids }}
  {{ ^jira_ids }}
  No associated tickets
  {{ /jira_ids }}
